datasets:
  files:
    Phishing sites dataset:
      source: G:/My Drive/URL-Phish_Dataset.csv
      metadata: {}
analysis:
  files:
    correlation_matrix:
      path: analysis/correlation_matrix.py
      metadata:
        fig_corr:
          type: figure
          path: images\correlation_matrix_fig_corr.png
        high_corr_df:
          type: dataframe
          path: data\correlation_matrix_high_corr_df.json
    feature_skewness:
      path: analysis/feature_skewness.py
      metadata:
        skew_summary_df:
          type: dataframe
          path: data\feature_skewness_skew_summary_df.json
        fig_skew:
          type: figure
          path: images\feature_skewness_fig_skew.png
    outlier_detection:
      path: analysis/outlier_detection.py
      metadata:
        fig_outliers:
          type: figure
          path: images\outlier_detection_fig_outliers.png
    model_comparison:
      path: analysis/model_comparison.py
      metadata:
        df:
          type: dataframe
          path: data\model_comparison_df.json
        fig:
          type: figure
          path: images\model_comparison_fig.png
ops:
  files:
    dvc_config:
      path: .dvc/config
      description: DVC configuration with DagsHub remote
    dvc_pipeline:
      path: dvc.yaml
      description: DVC pipeline configuration for data versioning and reproducible
        runs
    dockerfile:
      path: Dockerfile
      description: Dockerfile for the Streamlit ML App
    docker_compose:
      path: docker-compose.yml
      description: Docker Compose file containing Streamlit app and Jenkins
    jenkinsfile:
      path: Jenkinsfile
      description: Jenkins pipeline for CI/CD and Continuous Training
utils:
  files:
    feature_extractor:
      path: utils/feature_extractor.py
    phishtank_checker:
      path: utils/phishtank_checker.py
    content_inspector:
      path: utils/content_inspector.py
    domain_ssl_checker:
      path: utils/domain_ssl_checker.py
pipeline:
  stages:
    ingestion:
      elements:
        data_ingestion:
          path: pipeline/data_ingestion.py
    preprocessing:
      elements:
        data_cleaning:
          path: pipeline/data_cleaning.py
          depends_on:
          - ingestion.data_ingestion
        data_resampling:
          path: pipeline/data_resampling.py
          depends_on: []
    splitting:
      elements:
        data_splitting:
          path: pipeline/data_splitting.py
          depends_on:
          - preprocessing.data_cleaning
    training:
      elements:
        model_training:
          path: pipeline/model_training.py
          depends_on:
          - splitting.data_splitting
    inference:
      elements:
        inference:
          path: pipeline/inference.py
          depends_on:
          - utils.phishtank_checker
          - utils.content_inspector
          - utils.feature_extractor
          - utils.domain_ssl_checker
